WebShopOnl/Controllers/AboutUsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebShopOnl.Controllers
{
    public class AboutUsController : Controller
    {
        // GET: AboutUs
        public ActionResult Index()
        {
            return View();
        }
    }
}

WebShopOnl/Controllers/ContactController.cs
using Model.DAO;
using Model.EF;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebShopOnl.Controllers
{
    public class ContactController : Controller
    {
        // GET: Contact
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public JsonResult Send(string name, string mobile, string address, string email, string content)
        {
            var feedback = new Feedback();
            feedback.Name = name;
            feedback.Email = email;
            feedback.CreateDate = DateTime.Now;
            feedback.Phone = mobile;
            feedback.Content = content;
            feedback.Address = address;

            var id = new ContactDao().InsertFeedBack(feedback);
            if (id > 0)
            {
                return Json(new
                {
                    status = true
                });
                
            }

            else
                return Json(new
                {
                    status = false
                });

        }
    }
}

WebShopOnl/Controllers/NewsController.cs
using Model.DAO;
using Model.EF;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebShopOnl.Controllers
{
    public class NewsController : Controller
    {
        // GET: News
        public ActionResult Index()
        {
            var lstNew = new NewsDao().ListAllNews();
            return View(lstNew);
        }

        public ActionResult Detail(long id)
        {
            var news = new NewsDao().ViewDetail(id);
            return View(news);
        }
    }
}

WebShopOnl/Controllers/ProductController.cs
using Model.DAO;
using Model.EF;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebShopOnl.Models;

namespace WebShopOnl.Controllers
{
    
    public class ProductController : Controller
    {
        private const string CartSession = "CartSession";
        WebShopOnlDbContext db = new WebShopOnlDbContext();
        // GET: Product
        public ActionResult Index()
        {
            return View();
        }

        public PartialViewResult ProductCategory()
        {
            var model = new ProductCategoryDao().ListAll();
            return PartialView(model);
        }

        public ActionResult ProductByTheme (long CategoryID = 1)
        {
            List<Product> lstSp = db.Products.Where(x => x.CategoryID == CategoryID).OrderByDescending(x => x.ID).ToList();
            ViewBag.Category = db.ProductCategories.Find(CategoryID);

            
            return View(lstSp);
        }

        //chi tiet san pham

        public ActionResult Detail(long id)
        {
            var product = new ProductDao().ViewDetail(id);
            ViewBag.Category = new ProductCategoryDao().ViewDetail(product.CategoryID.Value);
            ViewBag.RelatedProducts = new ProductDao().ListRelatedProducts(id);
            return View(product);
        }

        //Tim kiem Jjson

        public JsonResult ListName(string q)
        {
            var data = new ProductDao().ListName(q);
            return Json(new
            {
                data = data,
                status = true
            }, JsonRequestBehavior.AllowGet);
        }

        //tim kiem

        public ActionResult Search(string keyword, int page = 1, int pageSize = 2)
        {
            int totalRecord = 0;
            var model = new ProductDao().Search(keyword, ref totalRecord, page, pageSize);

            ViewBag.Total = totalRecord;
            ViewBag.Page = page;
            ViewBag.Keyword = keyword;
            int maxPage = 5;
            int totalPage = 0;

            totalPage = (int)Math.Ceiling((double)(totalRecord / pageSize));
            ViewBag.TotalPage = totalPage;
            ViewBag.MaxPage = maxPage;
            ViewBag.First = 1;
            ViewBag.Last = totalPage;
            ViewBag.Next = page + 1;
            ViewBag.Prev = page - 1;


            return View(model);
        }

        //Thanh toan

        [HttpGet]
        public ActionResult Payment()
        {
            var cart = Session[CartSession];
            var list = new List<CartItem>();
            if (cart != null)
            {
                list = (List<CartItem>)cart;
            }
            return View(list);
        }

        [HttpPost]
        public ActionResult Payment(string shipName, string mobile, string address, string email)
        {
            var order = new Order();
            order.CreateDate = DateTime.Now;
            order.ShipAddress = address;
            order.ShipPhone = mobile;
            order.ShipName = shipName;
            order.ShipEmail = email;

            try
            {
                var id = new OrderDao().Insert(order);
                var cart = (List<CartItem>)Session[CartSession];
                var detailDao = new OrderDetailDao();
                decimal total = 0;
                foreach (var item in cart)
                {
                    var orderDetail = new OrderDetail();
                    orderDetail.ID = item.Product.ID;
                    orderDetail.OrderID = id;
                    orderDetail.Price = item.Product.Price;
                    orderDetail.Quantity = item.Quantity;
                    detailDao.Insert(orderDetail);

                    total += (item.Product.Price.GetValueOrDefault(0) * item.Quantity);
                }
               
            }
            catch (Exception ex)
            {
                //ghi log
                return Redirect("/loi-thanh-toan");
            }
            return Redirect("/Cart/Success");
        }
    }
}

WebShopOnl/Views/Shared/HeaderCart.cshtml
@model List<WebShopOnl.Models.CartItem>
<div class="position-relative cart-buy">
    <button class="cart">
        <a href="/Cart/Index"><i class="fas fa-shopping-cart"></i></a>
    </button>

    <span class="badge badge-dark num-product">@Model.Count</span>

</div>

WebShopOnl/Views/Shared/_Layout2.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="~/assets/client/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/assets/client/fontawesome/css/all.css" rel="stylesheet" />
    <link href="~/assets/client/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet" />
    <link href="~/assets/client/owlcarousel/assets/owl.theme.default.min.css" rel="stylesheet" />
    <link href="~/assets/client/css/jquery-ui.css" rel="stylesheet" />
    <link href="~/assets/client/css/main.css" rel="stylesheet" />
    <script src="~/assets/client/js/jquery.min.js"></script>
    <script src="~/assets/client/js/jquery-ui.js"></script>
    <script src="~/assets/client/owlcarousel/owl.carousel.min.js"></script>
    <script src="~/assets/client/js/popper.min.js"></script>
    <script src="~/assets/client/bootstrap/js/bootstrap.min.js"></script>
    @*<script src="~/assets/client/js/controller/cartController.js"></script>*@
    <link href="~/assets/client/css/main.css" rel="stylesheet" />
    <title>@ViewBag.Title</title>

</head>

<body>
    <div id="fb-root"></div>
    <script async defer crossorigin="anonymous" src="https://connect.facebook.net/vi_VN/sdk.js#xfbml=1&version=v10.0" nonce="bUgRVhHM"></script>
    <div id="wrapper">
        <div id="back-to-top"><i class="fas fa-arrow-up"></i></div>
        <div id="header" class="border-bottom bg-white sticky-top">
            <div class="container-xl ">
                <nav class="navbar navbar-expand-md navbar-light" id="">
                    <a href="@Url.Action("Index","Home")" class="navbar-brand">
                        
                        <img src="~/assets/client/images/logoo.jpg" alt="" />
                    </a>
                    <button class="navbar-toggler" data-toggle="collapse" data-target="#main-menu">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="main-menu">
                        <ul class="navbar-nav mr-auto">
                            <li class="nav-item">
                                <a href="/Home/Index" class="nav-link">Trang chủ</a>
                            </li>
                            <li class="nav-item">
                                <a href="/Product/Index" class="nav-link">Sản phẩm</a>
                            </li>
                            <li class="nav-item">
                                <a href="/News/Index" class="nav-link">Tin tức</a>
                            </li>
                            <li class="nav-item">
                                <a href="/AboutUs/Index" class="nav-link">Giới thiệu</a>
                            </li>
                            <li class="nav-item">
                                <a href="/Contact/Index" class="nav-link">Liên hệ</a>
                            </li>
                        </ul>

                        <!-- <input type="text" name="" id="" class="form-control"> -->
                        <div class="hd-search">
                            <button class="search"><i class="fas fa-search"></i></button>
                            <form action="/Product/Search" method="get">
                                <div class="input-group">
                                    <input type="text" name="keyword" id="txtKeyword" class="form-control" placeholder="tìm kiếm.....">
                                    <div class="input-group-append">
                                        <button class="btn btn-danger" type="submit" id="button-addon2">
                                            <i class="fas fa-search"></i>
                                        </button>
                                    </div>
                                </div>
                            </form>
                        </div>


                        <div class="account position-relative">
                            <button class="user">
                                <i class="fas fa-user"></i>
                            </button>

                            @{
                                var session = (WebShopOnl.Common.UserLogin)Session[WebShopOnl.Common.ComonConstants.USER_SESSION];
                            }
                            @if (session == null)
                            {
                                <ul class="acc">
                                    <li>
                                        <a href="/User/Login">Đăng nhập</a>
                                    </li>
                                    <li>
                                        <a href="/User/Register">Đăng ký</a>
                                    </li>
                                </ul>
                            }
                            else
                            {
                                <ul class="acc">
                                    <li>
                                        <a href="/User/Login">@session.UserName</a>
                                    </li>
                                    <li>
                                        <a href="/User/Logout">Thoát</a>
                                    </li>
                                </ul>
                            }


                        </div>


                        @{ Html.RenderAction("HeaderCart", "Home");}


                    </div>

                </nav>
            </div>
        </div>

        <!-- Content -->

        <div id="wp-content" class="container-xl my-5">

            <!-- NEW PRODUCT -->

            @RenderBody()

        </div>

        <!-- ----FOOTER----- -->


        <div id="footer" class="mt-5">
            <div class="container-xl pb-5">
                <div class=" row row-cols-md-3 mt-5">
                    <div class="col about-us">
                        <div class="logo mb-2">
                            <a href="Index.html">
                                <img src="assets/images/Logo.png" alt="">
                            </a>
                        </div>
                        <div class="address my-2">
                            Địa chỉ: Đường số 21 Phường Long Thạnh Mỹ Thành phố Thủ Đức(Quận 9 cũ)
                        </div>
                        <div class="number-phone my-2">
                            Số điện thoại: 094903490 - 08743294
                        </div>
                        <div class="email my-2">
                            Email: quoctien04022001@gmail.com
                        </div>
                    </div>
                    <div class="col linked">
                        <div class="row">
                            <div class="col-6">
                                <h5 class="title">Liên kết nhanh</h5>
                                <ul class="menu-footer">
                                    <li>
                                        <a href="">Chính sách bảo hành</a>
                                    </li>
                                    <li>
                                        <a href="">Chính sách thành viên</a>
                                    </li>
                                </ul>
                            </div>
                            <div class="col-6">
                                <h5 class="title">Danh mục</h5>
                                <ul class="menu-footer">
                                    <li>
                                        <a href="@Url.Action("Index","Home")">Trang chủ</a>
                                    </li>
                                    <li>
                                        <a href="@Url.Action("Index","Product")">Sản phẩm</a>
                                    </li>
                                    <li>
                                        <a href="@Url.Action("Index","News")">Tin tức</a>
                                    </li>
                                    <li>
                                        <a href="@Url.Action("Index","AboutUs")">Giới thiệu</a>
                                    </li>
                                    <li>
                                        <a href="@Url.Action("Index","Contact")">Liên hệ</a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="col">
                        <div class="fb-page" data-href="https://www.facebook.com/saonhapngu" data-tabs="" data-width="" data-height="" data-small-header="false" data-adapt-container-width="true" data-hide-cover="false" data-show-facepile="true">
                            <blockquote cite="https://www.facebook.com/saonhapngu" class="fb-xfbml-parse-ignore"><a href="https://www.facebook.com/saonhapngu">Sao nhập ngũ</a></blockquote>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>

    <script>
        $(document).ready(function () {
            $('.owl-carousel').owlCarousel({
                loop: true,
                autoplay: true,
                margin: 10,
                nav: true,
                responsive: {
                    0: {
                        items: 2
                    },
                    600: {
                        items: 2
                    },
                    1000: {
                        items: 4
                    }
                }
            })
        });
    </script>
    <script>
        $(document).ready(function () {
            $(window).scroll(function () {
                var _val = $('html,body').scrollTop();
                console.log(_val);
                if (_val > 100) {
                    $('#back-to-top').addClass('hien-backtop');
                } else {
                    $('#back-to-top').removeClass('hien-backtop');
                }
            });
            $('#back-to-top').click(function () {
                $('html,body').animate({
                    scrollTop: 0
                }, 1000);
            });
        });
    </script>

    <script>
        $(document).ready(function () {
            $('button.search').click(function () {
                $('button.search+form').fadeToggle(500);

                return false;
            });
        });
    </script>

    <script src="~/assets/client/js/controller/baseController.js"></script>
    @RenderSection("jsFooter", false);
</body>

</html>

WebShopOnl/Views/Shared/_LayoutHome.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="~/assets/client/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/assets/client/fontawesome/css/all.css" rel="stylesheet" />
    <link href="~/assets/client/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet" />
    <link href="~/assets/client/owlcarousel/assets/owl.theme.default.min.css" rel="stylesheet" />
    <link href="~/assets/client/css/jquery-ui.css" rel="stylesheet" />
    <link href="~/assets/client/css/main.css" rel="stylesheet" />
    <script src="~/assets/client/js/jquery.min.js"></script>
    <script src="~/assets/client/js/jquery-ui.js"></script>
    <script src="~/assets/client/owlcarousel/owl.carousel.min.js"></script>
    <script src="~/assets/client/js/popper.min.js"></script>
    <script src="~/assets/client/bootstrap/js/bootstrap.min.js"></script>
    @*<script src="~/assets/client/js/controller/cartController.js"></script>*@
    <title>@ViewBag.Title</title>

</head>

<body>
    <div id="fb-root"></div>
    <script async defer crossorigin="anonymous" src="https://connect.facebook.net/vi_VN/sdk.js#xfbml=1&version=v10.0" nonce="bUgRVhHM"></script>
    <div id="wrapper">
        <div id="back-to-top"><i class="fas fa-arrow-up"></i></div>
        <div id="header" class="border-bottom bg-white sticky-top">
            <div class="container-xl ">
                <nav class="navbar navbar-expand-md navbar-light" id="">
                    <a href="@Url.Action("Index","Home")" class="navbar-brand">
                        
                        <img src="~/assets/client/images/logoo.jpg" alt="" />
                        
                    </a>
                    <button class="navbar-toggler" data-toggle="collapse" data-target="#main-menu">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="main-menu">
                        <ul class="navbar-nav mr-auto">
                            <li class="nav-item">
                                <a href="/Home/Index" class="nav-link">Trang chủ</a>
                            </li>
                            <li class="nav-item">
                                <a href="/Product/Index" class="nav-link">Sản phẩm</a>
                            </li>
                            <li class="nav-item">
                                <a href="/News/Index" class="nav-link">Tin tức</a>
                            </li>
                            <li class="nav-item">
                                <a href="/AboutUs/Index" class="nav-link">Giới thiệu</a>
                            </li>
                            <li class="nav-item">
                                <a href="/Contact/Index" class="nav-link">Liên hệ</a>
                            </li>
                        </ul>

                        <!-- <input type="text" name="" id="" class="form-control"> -->
                        <div class="hd-search">
                            <button class="search"><i class="fas fa-search"></i></button>
                            <form action="/Product/Search" method="get">
                                <div class="input-group">
                                    <input type="text" name="keyword" id="txtKeyword" class="form-control" placeholder="tìm kiếm.....">
                                    <div class="input-group-append">
                                        <button class="btn btn-danger" type="button" id="button-addon2">
                                            <i class="fas fa-search"></i>
                                        </button>
                                    </div>
                                </div>
                            </form>
                        </div>


                        <div class="account position-relative">
                            <button class="user">
                                <i class="fas fa-user"></i>
                            </button>

                            @{
                                var session = (WebShopOnl.Common.UserLogin)Session[WebShopOnl.Common.ComonConstants.USER_SESSION];
                            }
                            @if (session == null)
                            {
                                <ul class="acc">
                                    <li>
                                        <a href="/User/Login">Đăng nhập</a>
                                    </li>
                                    <li>
                                        <a href="/User/Register">Đăng ký</a>
                                    </li>
                                </ul>
                            }
                            else
                            {
                                <ul class="acc">
                                    <li>
                                        <a href="/User/Login">@session.UserName</a>
                                    </li>
                                    <li>
                                        <a href="/User/Logout">Đăng xuất</a>
                                    </li>
                                </ul>
                            }

                        </div>


                        @{ Html.RenderAction("HeaderCart", "Home");}


                    </div>

                </nav>
            </div>
        </div>
        <div id="slide-carousel">
            <div id="slideshowHome" class="carousel slide carousel-fade " data-ride="carousel">
                <ol class="carousel-indicators">
                    <li data-target="#slideshowHome" data-slide-to="0" class="active"></li>
                    <li data-target="#slideshowHome" data-slide-to="1"></li>

                </ol>
                <div class="carousel-inner">
                    <div class="carousel-item active">
                        
                        <img src="~/assets/client/images/Banner-lon_2fb.jpg" class="d-block w-100" alt="" />

                    </div>
                    <div class="carousel-item">

                        <img src="~/assets/client/images/banner-web.png" class="d-block w-100" alt=""/>
                        
                    </div>
                </div>

            </div>
        </div>

        <!-- Content -->

        <div id="wp-content" class="container-xl my-5">

            <!-- NEW PRODUCT -->

            @RenderBody()

        </div>


        <!-- ----FOOTER----- -->


        <div id="footer" class="mt-5">
            <div class="container-xl pb-5">
                <div class=" row row-cols-md-3 mt-5">
                    <div class="col about-us">
                        <div class="logo mb-2">
                            <a href="Index.html">
                                <img src="assets/images/Logo.png" alt="">
                            </a>
                        </div>
                        <div class="address my-2">
                            Địa chỉ: Đường số 21 Phường Long Thạnh Mỹ Thành phố Thủ Đức(Quận 9 cũ) 
                        </div>
                        <div class="number-phone my-2">
                            Số điện thoại: 094903490 - 08743294
                        </div>
                        <div class="email my-2">
                            Email: quoctien04022001@gmail.com
                        </div>
                    </div>
                    <div class="col linked">
                        <div class="row">
                            <div class="col-6">
                                <h5 class="title">Liên kết nhanh</h5>
                                <ul class="menu-footer">
                                    <li>
                                        <a href="">Chính sách bảo hành</a>
                                    </li>
                                    <li>
                                        <a href="">Chính sách thành viên</a>
                                    </li>
                                </ul>
                            </div>
                            <div class="col-6">
                                <h5 class="title">Danh mục</h5>
                                <ul class="menu-footer">
                                    <li>
                                        <a href="@Url.Action("Index","Home")">Trang chủ</a>
                                    </li>
                                    <li>
                                        <a href="@Url.Action("Index","Product")">Sản phẩm</a>
                                    </li>
                                    <li>
                                        <a href="@Url.Action("Index","News")">Tin tức</a>
                                    </li>
                                    <li>
                                        <a href="@Url.Action("Index","AboutUs")">Giới thiệu</a>
                                    </li>
                                    <li>
                                        <a href="@Url.Action("Index","Contact")">Liên hệ</a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="col">
                        <div class="fb-page" data-href="https://www.facebook.com/saonhapngu" data-tabs="" data-width="" data-height="" data-small-header="false" data-adapt-container-width="true" data-hide-cover="false" data-show-facepile="true">
                            <blockquote cite="https://www.facebook.com/saonhapngu" class="fb-xfbml-parse-ignore"><a href="https://www.facebook.com/saonhapngu">Sao nhập ngũ</a></blockquote>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>


    <script>
        $(document).ready(function () {
            $(window).scroll(function () {
                var _val = $('html,body').scrollTop();
                console.log(_val);
                if (_val > 100) {
                    $('#back-to-top').addClass('hien-backtop');
                } else {
                    $('#back-to-top').removeClass('hien-backtop');
                }
            });
            $('#back-to-top').click(function () {
                $('html,body').animate({
                    scrollTop: 0
                }, 1000);
            });
        });
    </script>

    <script>
        $(document).ready(function () {
            $('button.search').click(function () {
                $('button.search+form').fadeToggle(500);

                return false;
            });
        });
    </script>
    <script>
        $(document).ready(function () {
            $('.owl-carousel').owlCarousel({
                loop: true,
                autoplay: true,
                margin: 10,
                nav: true,
                responsive: {
                    0: {
                        items: 2
                    },
                    600: {
                        items: 2
                    },
                    1000: {
                        items: 4
                    }
                }
            })
        });
    </script>

    <script src="~/assets/client/js/controller/baseController.js"></script>
    @RenderSection("jsFooter", false);
</body>

</html>